// packages/inspector-react/src/SpecSnapInspector.tsx
import { forwardRef, useEffect, useImperativeHandle, useCallback } from 'react';
import { createPortal } from 'react-dom';
import { TriggerButton } from './TriggerButton.js';
import { Panel } from './Panel.js';
import { useInspector } from './use-inspector.js';
import type {
  InspectorOptions,
  InspectorSnapshot,
  InspectorHandle,
  PanelPosition,
  Session,
  SpecSnapBundle,
  SaveResult
} from '@tw199501/specsnap-inspector-core';

export interface SpecSnapInspectorProps {
  scope?: InspectorOptions['scope'];
  position?: PanelPosition;
  trigger?: boolean;
  panelTitle?: string;
  onSave?: (bundle: SpecSnapBundle) => void | Promise<void>;
  onCopy?: (markdown: string) => void;
  onCapture?: (payload: { frameIndex: number; session: Session }) => void;
  onClear?: () => void;
  onOpen?: () => void;
  onClose?: () => void;
}

export interface SpecSnapInspectorHandle {
  open: () => void;
  close: () => void;
  toggle: () => void;
  startPicker: () => void;
  stopPicker: () => void;
  clearFrames: () => void;
  copyMarkdown: () => Promise<void>;
  saveBundle: () => Promise<SaveResult>;
  getSnapshot: () => InspectorSnapshot;
  /** Escape hatch for power users. */
  handle: InspectorHandle;
}

export const SpecSnapInspector = forwardRef<SpecSnapInspectorHandle, SpecSnapInspectorProps>(
  function SpecSnapInspector(props, ref) {
    const position = props.position ?? 'bottom-right';
    const showTrigger = props.trigger ?? true;
    const panelTitle = props.panelTitle ?? 'SpecSnap Inspector';

    const inspectorOptions: InspectorOptions = {
      position,
      trigger: showTrigger,
      panelTitle
    };
    if (props.scope !== undefined) inspectorOptions.scope = props.scope;
    if (props.onSave) inspectorOptions.onSave = props.onSave;
    if (props.onCopy) inspectorOptions.onCopy = props.onCopy;
    if (props.onCapture) inspectorOptions.onCapture = props.onCapture;
    if (props.onClear) inspectorOptions.onClear = props.onClear;
    if (props.onOpen) inspectorOptions.onOpen = props.onOpen;
    if (props.onClose) inspectorOptions.onClose = props.onClose;

    const { snapshot, handle } = useInspector(inspectorOptions);

    useEffect(() => {
      document.body.classList.toggle('specsnap-inspecting', snapshot.picking);
    }, [snapshot.picking]);

    useImperativeHandle(ref, () => ({
      open: handle.open,
      close: handle.close,
      toggle: handle.toggle,
      startPicker: handle.startPicker,
      stopPicker: handle.stopPicker,
      clearFrames: handle.clearFrames,
      copyMarkdown: handle.copyMarkdown,
      saveBundle: handle.saveBundle,
      getSnapshot: handle.getSnapshot,
      handle
    }), [handle]);

    const onCopy = useCallback(async () => {
      handle.stopPicker();
      await handle.copyMarkdown();
      await handle.saveBundle();
    }, [handle]);

    const onTogglePicker = useCallback(() => {
      if (snapshot.picking) handle.stopPicker();
      else handle.startPicker();
    }, [handle, snapshot.picking]);

    return (
      <>
        {showTrigger && !snapshot.visible && (
          <TriggerButton
            position={position}
            onClick={handle.toggle}
          />
        )}
        {snapshot.visible && typeof document !== 'undefined' && createPortal(
          <Panel
            snapshot={snapshot}
            position={position}
            title={panelTitle}
            onClose={handle.close}
            onTogglePicker={onTogglePicker}
            onClear={handle.clearFrames}
            onCopy={onCopy}
          />,
          document.body
        )}
      </>
    );
  }
);

// packages/inspector-vue/src/SpecSnapInspector.vue
<template>
  <TriggerButton
    v-if="showTrigger && !snapshot.visible"
    :position="resolvedPosition"
    @click="handle.toggle()"
  />

  <Teleport to="body">
    <Panel
      v-if="snapshot.visible"
      :snapshot="snapshot"
      :position="resolvedPosition"
      :title="resolvedTitle"
      @close="handle.close()"
      @toggle-picker="togglePicker"
      @clear="handle.clearFrames()"
      @copy="onCopyClick"
    />
  </Teleport>
</template>

<script setup lang="ts">
import { watch, computed } from 'vue';
import TriggerButton from './TriggerButton.vue';
import Panel from './Panel.vue';
import { useInspector } from './use-inspector.js';
import type {
  PanelPosition,
  InspectorOptions,
  InspectorHandle,
  SpecSnapBundle,
  Session
} from '@tw199501/specsnap-inspector-core';

const props = defineProps<{
  scope?: InspectorOptions['scope'];
  position?: PanelPosition;
  trigger?: boolean;
  panelTitle?: string;
  onSave?: (bundle: SpecSnapBundle) => void | Promise<void>;
}>();

const resolvedPosition = computed<PanelPosition>(() => props.position ?? 'bottom-right');
const resolvedTitle = computed<string>(() => props.panelTitle ?? 'SpecSnap Inspector');
const showTrigger = computed<boolean>(() => props.trigger ?? true);

const emit = defineEmits<{
  save: [SpecSnapBundle];
  copy: [string];
  capture: [{ frameIndex: number; session: Session }];
  clear: [];
  open: [];
  close: [];
}>();

const inspectorOptions: InspectorOptions = {
  position: resolvedPosition.value,
  trigger: showTrigger.value,
  panelTitle: resolvedTitle.value,
  onCopy: (md) => emit('copy', md),
  onCapture: (payload) => emit('capture', payload),
  onClear: () => emit('clear'),
  onOpen: () => emit('open'),
  onClose: () => emit('close')
};
if (props.scope !== undefined) inspectorOptions.scope = props.scope;
if (props.onSave) inspectorOptions.onSave = props.onSave;

const { snapshot, handle } = useInspector(inspectorOptions);

watch(() => snapshot.value.picking, (on) => {
  document.body.classList.toggle('specsnap-inspecting', on);
});

function togglePicker(): void {
  if (snapshot.value.picking) handle.stopPicker();
  else handle.startPicker();
}

async function onCopyClick(): Promise<void> {
  await handle.copyMarkdown();
  await handle.saveBundle();
}

defineExpose({
  open: () => handle.open(),
  close: () => handle.close(),
  toggle: () => handle.toggle(),
  startPicker: () => handle.startPicker(),
  stopPicker: () => handle.stopPicker(),
  clearFrames: () => handle.clearFrames(),
  getSnapshot: () => handle.getSnapshot(),
  handle: handle as InspectorHandle
});
</script>
