// packages/inspector-vue/src/TriggerButton.vue
<template>
  <button
    type="button"
    class="specsnap-inspector-trigger"
    :data-position="position"
    aria-label="Open SpecSnap Inspector"
    @click="$emit('click')"
  >
    <slot>◎</slot>
  </button>
</template>

<script setup lang="ts">
import type { PanelPosition } from '@tw199501/specsnap-inspector-core';

defineProps<{
  position: PanelPosition;
}>();

defineEmits<{ click: [] }>();
</script>

// packages/inspector-react/src/TriggerButton.tsx
import type { PanelPosition } from '@tw199501/specsnap-inspector-core';

export interface TriggerButtonProps {
  position: PanelPosition;
  onClick: () => void;
}

export function TriggerButton({ position, onClick }: TriggerButtonProps) {
  return (
    <button
      type="button"
      className="specsnap-inspector-trigger"
      data-position={position}
      aria-label="Open SpecSnap Inspector"
      onClick={onClick}
    >
      ◎
    </button>
  );
}
